#!/bin/bash
# Commands to check ECS tasks and logs

CLUSTER="kestra-cluster"
SERVICE_NAME="KestraEcsServiceStack-KestraService70B26FFB-k7TIHpEfZGDM"
LOG_GROUP="/aws/ecs/kestra-logs"
REGION="eu-central-1"
PROFILE="data-sandbox"

echo "=============================================="
echo "📋 Quick Commands to Check ECS Tasks"
echo "=============================================="
echo ""

echo "1️⃣  Scale up service to start tasks:"
echo "   aws ecs update-service \\"
echo "     --cluster $CLUSTER \\"
echo "     --service $SERVICE_NAME \\"
echo "     --desired-count 1 \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE"
echo ""

echo "2️⃣  List running tasks:"
echo "   aws ecs list-tasks \\"
echo "     --cluster $CLUSTER \\"
echo "     --service-name $SERVICE_NAME \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE"
echo ""

echo "3️⃣  Get task details (replace TASK_ARN):"
echo "   TASK_ARN=\$(aws ecs list-tasks --cluster $CLUSTER --service-name $SERVICE_NAME --region $REGION --profile $PROFILE --query 'taskArns[0]' --output text)"
echo "   aws ecs describe-tasks \\"
echo "     --cluster $CLUSTER \\"
echo "     --tasks \$TASK_ARN \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE \\"
echo "     --query 'tasks[0].containers[*].{Name:name,Status:lastStatus,ExitCode:exitCode,Reason:reason}' \\"
echo "     --output table"
echo ""

echo "4️⃣  Check GitSync logs (last 50 lines):"
echo "   aws logs tail $LOG_GROUP \\"
echo "     --since 10m \\"
echo "     --filter-pattern 'GitSync' \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE"
echo ""

echo "5️⃣  Check SshInit logs:"
echo "   aws logs tail $LOG_GROUP \\"
echo "     --since 10m \\"
echo "     --filter-pattern 'SshInit' \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE"
echo ""

echo "6️⃣  Follow all logs in real-time:"
echo "   aws logs tail $LOG_GROUP \\"
echo "     --follow \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE"
echo ""

echo "7️⃣  Check for SSH key errors:"
echo "   aws logs filter-log-events \\"
echo "     --log-group-name $LOG_GROUP \\"
echo "     --filter-pattern 'error' \\"
echo "     --region $REGION \\"
echo "     --profile $PROFILE \\"
echo "     --max-items 20 \\"
echo "     --query 'events[*].message' \\"
echo "     --output text"
echo ""

echo "=============================================="
echo "🚀 Quick Start: Scale up and check"
echo "=============================================="
echo ""
echo "Run this to scale up and then check status:"
echo ""
echo "aws ecs update-service --cluster $CLUSTER --service $SERVICE_NAME --desired-count 1 --region $REGION --profile $PROFILE && sleep 30 && ./scripts/check-task-status.sh"
echo ""

