#!/bin/bash
# Explain why tasks aren't running and how to fix it

echo "📚 Understanding: Why Tasks Aren't Running"
echo "==========================================="
echo ""
echo "In AWS ECS, here's how it works:"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 1. Task Definition (Blueprint)                 │"
echo "│    Created by: KestraEcsTaskStack             │"
echo "│    Defines: containers, CPU, memory, etc.     │"
echo "│    Status: Just a template, doesn't run       │"
echo "└─────────────────────────────────────────────────┘"
echo "                    ↓"
echo "┌─────────────────────────────────────────────────┐"
echo "│ 2. ECS Service (Task Manager)                   │"
echo "│    Created by: KestraEcsServiceStack            │"
echo "│    Uses: Task Definition                        │"
echo "│    Does: Creates and manages tasks              │"
echo "│    Keeps: desiredCount tasks running            │"
echo "└─────────────────────────────────────────────────┘"
echo "                    ↓"
echo "┌─────────────────────────────────────────────────┐"
echo "│ 3. Tasks (Running Containers)                   │"
echo "│    Created by: ECS Service                      │"
echo "│    Uses: Task Definition                        │"
echo "│    Status: Actual running containers            │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Common Misconception:"
echo "   'Tasks' are NOT a separate stack!"
echo "   Tasks are created AUTOMATICALLY by the Service"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Why Tasks Might Not Be Running:"
echo ""
echo "1. Service Not Deployed"
echo "   → Deploy: npx cdk deploy KestraEcsServiceStack"
echo "   → Without service, no tasks will be created"
echo ""
echo "2. Service Deployed But Tasks Failing"
echo "   → Check service events for errors"
echo "   → Tasks start but immediately stop"
echo "   → Common causes:"
echo "     • Secrets not accessible"
echo "     • EFS mount issues"
echo "     • Container health check failing"
echo "     • Insufficient resources"
echo ""
echo "3. Service Deployed But desiredCount = 0"
echo "   → Service exists but not starting tasks"
echo "   → Check service configuration"
echo ""
echo "4. Tasks Starting But Stopping Immediately"
echo "   → Check CloudWatch logs"
echo "   → Check container exit codes"
echo "   → Review service events"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ To Get Tasks Running:"
echo ""
echo "Step 1: Ensure Task Definition exists"
echo "   npx cdk deploy KestraEcsTaskStack"
echo ""
echo "Step 2: Deploy the Service (THIS CREATES TASKS)"
echo "   npx cdk deploy KestraEcsServiceStack"
echo ""
echo "Step 3: Service will automatically create tasks"
echo "   → Service reads desiredCount (currently set to 1)"
echo "   → Service uses Task Definition to create tasks"
echo "   → Tasks start running"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Key Point:"
echo "   You don't 'deploy tasks' separately"
echo "   You deploy the SERVICE, and it creates tasks"
echo ""
echo "   Task Definition = Recipe"
echo "   Service = Chef (creates tasks from recipe)"
echo "   Tasks = The dishes (created automatically)"

