#!/bin/bash
# Guide to prevent service deletion during deployment

echo "🛡️  Preventing Service Deletion During Deployment"
echo "=================================================="
echo ""
echo "Issue: Service gets deleted when deploying"
echo ""
echo "Possible Causes:"
echo "1. Service name conflict (old service from ALB stack)"
echo "2. CloudFormation replacement (resource changes)"
echo "3. Stack deletion/recreation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Solution Applied:"
echo "   → Added deletion protection to the service"
echo "   → Service cannot be deleted via CDK/CloudFormation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Before Deploying - Check for Conflicts:"
echo ""
echo "Run this to check for existing services:"
echo "  ./scripts/check-service-conflicts.sh"
echo ""
echo "If you find a conflicting service from the old ALB stack:"
echo ""
echo "Option 1: Delete the old service manually"
echo "  aws ecs update-service \\"
echo "    --cluster kestra-cluster \\"
echo "    --service <old-service-name> \\"
echo "    --desired-count 0 \\"
echo "    --region eu-central-1"
echo ""
echo "  aws ecs delete-service \\"
echo "    --cluster kestra-cluster \\"
echo "    --service <old-service-name> \\"
echo "    --region eu-central-1"
echo ""
echo "Option 2: Import existing service into CDK"
echo "  (More complex - requires cdk import)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 Safe Deployment Steps:"
echo ""
echo "1. Check for conflicts:"
echo "   ./scripts/check-service-conflicts.sh"
echo ""
echo "2. If conflicts found, resolve them first"
echo ""
echo "3. Deploy with deletion protection (now enabled):"
echo "   npx cdk deploy KestraEcsServiceStack --require-approval never"
echo ""
echo "4. If deployment still tries to delete:"
echo "   - Check CloudFormation events for details"
echo "   - The deletion protection will prevent accidental deletion"
echo "   - You may need to manually disable deletion protection first"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Note:"
echo "   Deletion protection prevents deletion via CDK/CloudFormation"
echo "   To delete, you must first disable protection:"
echo "   aws ecs update-service \\"
echo "     --cluster kestra-cluster \\"
echo "     --service <service-name> \\"
echo "     --no-enable-deletion-protection \\"
echo "     --region eu-central-1"

